### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by alrawi** [vitolimandibhrata/aws-lambda-numpy#2]
Hi,
I cloned your repo and tried to import a numpy in a test file but I got the following error. I am doing this for debugging purposes because I am having issues when I deploy to a lambda application.

#### My code (test.py):
`import numpy as np`
`print np.version`

#### Error:
`Traceback (most recent call last):`
`  File "test.py", line 1, in <module>`
`    import numpy as np`
`  File "/home/ubuntu/collect/aws-lambda-numpy/numpy/__init__.py", line 180, in <module>`
`    from . import add_newdocs`
`  File "/home/ubuntu/collect/aws-lambda-numpy/numpy/add_newdocs.py", line 13, in <module>`
`    from numpy.lib import add_newdoc`
`  File "/home/ubuntu/collect/aws-lambda-numpy/numpy/lib/__init__.py", line 8, in <module>`
`    from .type_check import *`
`  File "/home/ubuntu/collect/aws-lambda-numpy/numpy/lib/type_check.py", line 11, in <module>`
`    import numpy.core.numeric as _nx`
`  File "/home/ubuntu/collect/aws-lambda-numpy/numpy/core/__init__.py", line 14, in <module>`
`    from . import multiarray`
`ImportError: libptf77blas.so.3: cannot open shared object file: No such file or directory`

Any suggestions?

**Comment by vitolimandibhrata** [comment]
It seems that you run the code in your local development environment.

The code must be run in an AWS Lambda function as the NumPy library has been compiled to load the  `libptf77blas.so.3` file from `/var/task/lib/`.

`/var/task/` folder is the working directory of the AWS Lambda function.

Alternatively, you can copy the `/lib` folder in this project to the `/var/task/` folder  in your local development environment.

**Comment by hashamMunir** [comment]
How Can I use this in case of python3.6.

**Comment by kybrdbnd** [comment]
https://serverlesscode.com/post/deploy-scikitlearn-on-lamba/
follow this, just instead of python2.7 replace it with python3.6
